In [1]:
import numpy as np
import pandas as pd 
import datetime
import re

monthh = datetime.datetime.now().strftime("%m")
month=int(monthh)

yearr=datetime.datetime.now().strftime("%Y")
year=int(yearr)

print(year)

2020

In [2]:
df=pd.read_csv('dates_out.csv')

k=0
dff=pd.DataFrame(columns=['sentence'])
for i in range(400,900):
    x=df['sentence'][i]
    x=x.lower()
    dff.loc[k]=x
    k=k+1

In [3]:
import re
dic={'jan ':1,'january':1,'feb ':2,'february':2,'mar ':3,'march':3,'apr ':4,'april':4,'may':5,'jun ':6,'june':6,'jul ':7,'july':7,'aug ':8,'august':8,'sep ':9,'sept ':9,'september':9,'oct ':10,'october':10,'nov ':11,'november':11,'dec ':12,'december':12}

latr={'later':1,'prior':-1,'after':1,'from':1}

dates={'one':1,'first':1,'second':2,'two':2,'three':3,'third':3,'four':4,'fourth':4,'five':5,'fifth':5,'six':6,'sixth':6,'seven':7,'seventh':7,'eight':8,'eighth':8,'nine':9,'nineth':9,'ten':10,'tenth':10,'eleven':11,'twelve':12,'twelfth':12,'thirteen':13,'thirteenth':13,'fourteenth':14,'fifteenth':15,'sixteenth':16,'fourteen':14,'fifteen':15,'sixteen':16,'seventeen':17,'seventeenth':17,'eighteen':18,'eighteenth':18,'nineteen':19,'nineteenth':19,'twenty':20,'twenty one':21,'twenty first':21,'twenty second':22,'twenty two':22,'twenty third':23,'twenty three':23,'twenty four':24,'twenty five':25,'twenty six':26,'twenty seven':27,'twenty eight':28,'twenty nine':29,'thirty':30,'thirty first':31,'thirty one':31}

In [4]:
for i in range(0,500):
    yearr=datetime.datetime.now().strftime("%Y")
    year=int(yearr)
    x=dff['sentence'][i]
    x=x+" "
    srch=re.search(r'((one|two|three|four|five|fifth|six|seven|eight|nine|ten)?(st|nd|rd|th)?(\s)?(day\s|days)?(\s)?(later|prior|after|from)?(\s)?(of|to)?(\s)?(one|first|second|two|three|third|four|fourth|five|fifth|six|sixth|seven|seventh|eighth|eight|nine|nineth|ten|tenth|eleven|eleventh|twelve|twelfth|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twentieth|twenty|twenty\sone|twenty\sfirst|twenty\ssecond|twenty\stwo|twenty\sthird|twenty\sthree|twenty\sfour|twenty\sfive|twenty\ssix|twenty\sseven|twenty\seight|twenty\snine|thirty|thirty\sfirst|thirty\sone)?(st|nd|rd|th)?(\s)?(jan\s|january|feb\s|february|mar\s|march|apr\s|april|may|jun\s|june|jul\s|july|aug\s|august|sep\s|sept\s|september|oct\s|october|nov\s|november|dec\s|december))',x)
    if srch:
        year_srch=re.search(r'(([0-9]{1,4}(\s))$)',x)
        if ((srch.group(2)!=None) and (srch.group(7)!=None) and (srch.group(11)!=None) and (srch.group(14)!=None) ):
            actl_date=0
            actl_mon=0
            actl_year=0
            print("xxxxxxxxxxxxxxxxxxx",x)
            datt=srch.group(2)

            ltr=srch.group(7)
            date=srch.group(11)
            mon=srch.group(14)
                

            for l,mm in dates.items():
                if l==datt:
                    actl_date=mm
                    #print("actlllllll",actl_date)
                    break


            for p,k in dates.items():
                if p==date:
                    act_dat=k
                    break

            for pp,kk in dic.items():
                if pp==mon:
                    actl_mon=kk

            if month>actl_mon:
                year=year+1
                
            if year_srch:
                yer=year_srch.group(0)
                year=int(yer)

            d=datetime.date(year,actl_mon,act_dat)
            #print("ddddddddd",d)

            y=d+datetime.timedelta(actl_date)

            print(y)

xxxxxxxxxxxxxxxxxxx four day later of twenty second september
2020-09-26
xxxxxxxxxxxxxxxxxxx nine day later to fifth august
2020-08-14
xxxxxxxxxxxxxxxxxxx six days later ten june
2020-06-16
xxxxxxxxxxxxxxxxxxx nine day later to two february
2021-02-11
xxxxxxxxxxxxxxxxxxx eight day later of seven may
2020-05-15
xxxxxxxxxxxxxxxxxxx five days later to six nov
2020-11-11
xxxxxxxxxxxxxxxxxxx two day later twenty third may
2020-05-25
xxxxxxxxxxxxxxxxxxx five days later to twelveth september
2020-09-17
xxxxxxxxxxxxxxxxxxx six day after twenty third may
2020-05-29
xxxxxxxxxxxxxxxxxxx three days later eighteen september
2020-09-21
xxxxxxxxxxxxxxxxxxx four days later to sixteenth august
2020-08-20
xxxxxxxxxxxxxxxxxxx ten day later twenty first apr
2020-05-01
xxxxxxxxxxxxxxxxxxx ten day later nineteen sept
2020-09-29
xxxxxxxxxxxxxxxxxxx seven day later twenty third march
2020-03-30
xxxxxxxxxxxxxxxxxxx three days later twenty two june
2020-06-25
xxxxxxxxxxxxxxxxxxx one days later of fourteenth feb
2021-02-15
xxxxxxxxxxxxxxxxxxx three day later seventh nov
2020-11-10
xxxxxxxxxxxxxxxxxxx five days later of twenty one november
2020-11-26
xxxxxxxxxxxxxxxxxxx eight day later of sixteen july
2020-07-24
xxxxxxxxxxxxxxxxxxx ten days later two february
2021-02-12
xxxxxxxxxxxxxxxxxxx three days later twenty eight may 2029
2029-05-31
xxxxxxxxxxxxxxxxxxx seven day later twenty six february 2001
2001-03-05
xxxxxxxxxxxxxxxxxxx nine day later to six may 2031
2031-05-15
xxxxxxxxxxxxxxxxxxx fifth day after fifteen nov 2014
2014-11-20
xxxxxxxxxxxxxxxxxxx three day later eleven march 2003
2003-03-14
xxxxxxxxxxxxxxxxxxx three days later twenty eight november 2014
2014-12-01
xxxxxxxxxxxxxxxxxxx two days later thirteenth august 2020
2020-08-15
xxxxxxxxxxxxxxxxxxx four days later to twenty second feb 2018
2018-02-26
xxxxxxxxxxxxxxxxxxx six days later of twenty five march 2193
2193-03-31
xxxxxxxxxxxxxxxxxxx three days later twenty four apr 2040
2040-04-27
xxxxxxxxxxxxxxxxxxx nine day later to fourth december 2032
2032-12-13
xxxxxxxxxxxxxxxxxxx ten day later twenty eight january 2019
2019-02-07
xxxxxxxxxxxxxxxxxxx five days later of seventh oct 2004
2004-10-12
xxxxxxxxxxxxxxxxxxx five days later of thirteen november 2039
2039-11-18
xxxxxxxxxxxxxxxxxxx three days later twenty five july 2022
2022-07-28
xxxxxxxxxxxxxxxxxxx six day after four september 2023
2023-09-10
xxxxxxxxxxxxxxxxxxx nine day later to twenty eight sept 2193
2193-10-07
xxxxxxxxxxxxxxxxxxx seven days later seventeenth jun 2002
2002-06-24
xxxxxxxxxxxxxxxxxxx seven days later seven october 2001
2001-10-14
xxxxxxxxxxxxxxxxxxx six days later of fourteenth march 2002
2002-03-20
xxxxxxxxxxxxxxxxxxx six day after fifteen september 2029
2029-09-21
xxxxxxxxxxxxxxxxxxx ten days later twelve apr 2032
2032-04-22
xxxxxxxxxxxxxxxxxxx five days later of twenty one dec 2020
2020-12-26